-- MySQL Script generated by MySQL Workbench
-- Fri Aug  1 12:50:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sieco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sieco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sieco` DEFAULT CHARACTER SET utf8 ;
USE `sieco` ;

-- -----------------------------------------------------
-- Table `sieco`.`equipo_herramienta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sieco`.`equipo_herramienta` ;

CREATE TABLE IF NOT EXISTS `sieco`.`equipo_herramienta` (
  `id_equipo_herramienta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fecha_incorporacion` DATE NOT NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`id_equipo_herramienta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sieco`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sieco`.`material` ;

CREATE TABLE IF NOT EXISTS `sieco`.`material` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `unidad_medida` VARCHAR(30) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`id_material`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sieco`.`supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sieco`.`supervisor` ;

CREATE TABLE IF NOT EXISTS `sieco`.`supervisor` (
  `id_supervisor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_supervisor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sieco`.`obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sieco`.`obra` ;

CREATE TABLE IF NOT EXISTS `sieco`.`obra` (
  `id_obra` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `supervisor_id` INT NOT NULL,
  PRIMARY KEY (`id_obra`),
  INDEX `fk_obra_supervisor1_idx` (`supervisor_id` ASC) VISIBLE,
  CONSTRAINT `fk_obra_supervisor1`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `sieco`.`supervisor` (`id_supervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sieco`.`cuadrilla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sieco`.`cuadrilla` ;

CREATE TABLE IF NOT EXISTS `sieco`.`cuadrilla` (
  `id_cuadrilla` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `obra_id` INT NOT NULL,
  PRIMARY KEY (`id_cuadrilla`),
  INDEX `fk_cuadrilla_obra_idx` (`obra_id` ASC) VISIBLE,
  CONSTRAINT `fk_cuadrilla_obra`
    FOREIGN KEY (`obra_id`)
    REFERENCES `sieco`.`obra` (`id_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sieco`.`solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sieco`.`solicitud` ;

CREATE TABLE IF NOT EXISTS `sieco`.`solicitud` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cuadrilla_id` INT NOT NULL,
  `supervisor_id` INT NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `fk_solicitud_supervisor1_idx` (`supervisor_id` ASC) VISIBLE,
  INDEX `fk_solicitud_cuadrilla1_idx` (`cuadrilla_id` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_supervisor`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `sieco`.`supervisor` (`id_supervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_cuadrilla`
    FOREIGN KEY (`cuadrilla_id`)
    REFERENCES `sieco`.`cuadrilla` (`id_cuadrilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sieco`.`solicitud_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sieco`.`solicitud_detalle` ;

CREATE TABLE IF NOT EXISTS `sieco`.`solicitud_detalle` (
  `id_solicitud_detalle` INT NOT NULL AUTO_INCREMENT,
  `solicitud_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `equipo_id` INT NOT NULL,
  `cantidad_solicitada` INT NOT NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`id_solicitud_detalle`),
  INDEX `fk_solicitud_detalle_solicitud1_idx` (`solicitud_id` ASC) VISIBLE,
  INDEX `fk_solicitud_detalle_material1_idx` (`material_id` ASC) VISIBLE,
  INDEX `fk_solicitud_detalle_equipo_herramienta1_idx` (`equipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_detalle_solicitud1`
    FOREIGN KEY (`solicitud_id`)
    REFERENCES `sieco`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_detalle_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `sieco`.`material` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_detalle_equipo_herramienta1`
    FOREIGN KEY (`equipo_id`)
    REFERENCES `sieco`.`equipo_herramienta` (`id_equipo_herramienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sieco`.`asignacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sieco`.`asignacion` ;

CREATE TABLE IF NOT EXISTS `sieco`.`asignacion` (
  `id_asignacion` INT NOT NULL AUTO_INCREMENT,
  `solicitud_id` INT NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `estado_entrega` ENUM('pendiente', 'entregado', 'devuelto') NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`id_asignacion`),
  INDEX `fk_asignacion_solicitud1_idx` (`solicitud_id` ASC) VISIBLE,
  CONSTRAINT `fk_asignacion_solicitud1`
    FOREIGN KEY (`solicitud_id`)
    REFERENCES `sieco`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
